[package]
name = "tinycc-macro-bindgen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full", "parsing"] }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "tinycc-macro-bindgen"
path = "src/main.rs"
